FROM seataio/seata-server:1.7.1 

LABEL maintainer="491861364@qq.com"

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl  && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
